/* =========================================================================
   LUDB · 电影数据
   -------------------------------------------------------------------------
   全站唯一需要改的文件。新增一部电影 = 复制一个 { } 对象，改字段即可，
   海报放 assets/posters/ 里，再把 poster 路径指过去。
   字段说明见 README.md。

   ⚠️ 占位数据说明：
   用户确认尚无个人评分：myScore 全部为 null，scoreStatus 为 unrated。
   scoreStatus 为 placeholder 时显示「待评」且不排名；填写真实评分后改为 rated。
   不保留占位数值时，可用 myScore: null、scoreStatus: "unrated"。
   markedAt（标记日期）只有《奥本海默》26.09.19 和《盗梦空间》26.09.22
   来自你的清单，其余五部是按顺序补的占位日期。
   未提供标记日期的影片保持 null，不补猜测日期。
   review（短评）留空即不显示，填了才会出现在详情里。
   ========================================================================= */

window.LMDB = {
  meta: {
    siteName: "LUDB",
    subtitle: "MOVIE DATABASE",
    tagline: "我看过的电影，都记在这里。",
    owner: "NiKyrie",
    updatedAt: "2026-10-02",
    ratingsRecordedAt: "2026-10-02",
    ratingsNote: "IMDb／豆瓣为公开页面的收录快照，可能滞后，非实时评分；点击详情中的来源查看最新分数。",
  },

  movies: [
    {
      id: "shoplifters",
      title: "小偷家族",
      originalTitle: "万引き家族",
      enTitle: "Shoplifters",
      year: 2018,
      director: "是枝裕和",
      cast: ["中川雅也", "安藤樱", "松冈茉优", "城桧吏"],
      genres: ["剧情", "家庭", "犯罪"],
      country: "日本",
      runtime: 121,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 7.9,
      doubanScore: 8.7,
      imdbUrl: "https://www.imdb.com/title/tt8075192/",
      doubanUrl: "https://movie.douban.com/subject/27622447/",
      markedAt: "2026-09-05",
      poster: "assets/posters/shoplifters.jpg",
      posterPreview: "assets/posters/shoplifters-display.jpg",
      posterThumb: "assets/posters/shoplifters-thumb.jpg",
      backdrop: "assets/backdrops/shoplifters.jpg",
      backdropPosition: "50% 60%",
      backdropPositionMobile: "50% 60%",
      tagline: "我们选择成为一家人。",
      summary:
        "东京下町的一间老旧平房里，靠偷窃和零工拼凑生活的一家人。一个冬夜，他们收留了在公寓走廊里冻着的小女孩，这个由选择组成的家庭开始出现裂缝。",
      review: "",
    },
    {
      id: "umimachi",
      title: "海街日记",
      originalTitle: "海街diary",
      enTitle: "Our Little Sister",
      year: 2015,
      director: "是枝裕和",
      cast: ["绫濑遥", "长泽雅美", "夏帆", "广濑铃"],
      genres: ["剧情", "家庭"],
      country: "日本",
      runtime: 128,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 7.6,
      doubanScore: 8.8,
      imdbUrl: "https://www.imdb.com/title/tt3756788/",
      doubanUrl: "https://movie.douban.com/subject/25895901/",
      markedAt: "2026-09-07",
      poster: "assets/posters/umimachi.jpg",
      posterPreview: "assets/posters/umimachi-display.jpg",
      posterThumb: "assets/posters/umimachi-thumb.jpg",
      backdrop: "assets/backdrops/umimachi.jpg",
      backdropPosition: "50% 40%",
      tagline: "梅酒熟了，四季也走完了。",
      summary:
        "镰仓的老宅、四姐妹和一坛梅酒。父亲葬礼之后，长女把同父异母的妹妹接回了家，四季轮转里，被留下的伤口一点点被日常填平。",
      review: "",
    },
    {
      id: "aruitemo",
      title: "步履不停",
      originalTitle: "歩いても 歩いても",
      enTitle: "Still Walking",
      year: 2008,
      director: "是枝裕和",
      cast: ["阿部宽", "树木希林", "夏川结衣", "江原由希子"],
      genres: ["剧情", "家庭"],
      country: "日本",
      runtime: 115,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 7.9,
      doubanScore: 8.8,
      imdbUrl: "https://www.imdb.com/title/tt1087578/",
      doubanUrl: "https://movie.douban.com/subject/2222996/",
      markedAt: "2026-09-09",
      poster: "assets/posters/aruitemo.jpg",
      posterPreview: "assets/posters/aruitemo-display.jpg",
      posterThumb: "assets/posters/aruitemo-thumb.jpg",
      backdrop: "assets/backdrops/aruitemo.jpg",
      backdropPosition: "50% 40%",
      tagline: "人生总是慢半拍。",
      summary:
        "长子忌日，一家人回到海边小镇的老家。母亲在厨房里炸玉米天妇罗，父亲沉默着待在诊室，次子带着再婚的妻子和孩子走进了那间一直没变过的厨房。",
      review: "",
    },
    {
      id: "kiseki",
      title: "奇迹",
      originalTitle: "奇跡",
      enTitle: "I Wish",
      year: 2011,
      director: "是枝裕和",
      cast: ["前田航基", "前田旺志郎", "大塚宁宁", "小田切让"],
      genres: ["剧情", "家庭"],
      country: "日本",
      runtime: 128,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 7.4,
      doubanScore: 8.8,
      imdbUrl: "https://www.imdb.com/title/tt1650453/",
      doubanUrl: "https://movie.douban.com/subject/4889554/",
      markedAt: "2026-09-12",
      poster: "assets/posters/kiseki.jpg",
      posterPreview: "assets/posters/kiseki-display.jpg",
      posterThumb: "assets/posters/kiseki-thumb.jpg",
      backdrop: "assets/backdrops/kiseki.jpg",
      backdropPosition: "50% 45%",
      backdropPositionMobile: "50% 45%",
      tagline: "许愿的那一刻，就是奇迹。",
      summary:
        "父母分开后，兄弟俩一个跟着妈妈去了鹿儿岛，一个跟着爸爸留在福冈。新干线的第一次交汇被传说成许愿会实现的一刻，两群孩子各自带着愿望出发。",
      review: "",
    },
    {
      id: "interstellar",
      title: "星际穿越",
      originalTitle: "Interstellar",
      enTitle: "Interstellar",
      year: 2014,
      director: "克里斯托弗·诺兰",
      cast: ["马修·麦康纳", "安妮·海瑟薇", "杰西卡·查斯坦", "迈克尔·凯恩"],
      genres: ["科幻", "冒险", "剧情"],
      country: "美国",
      runtime: 169,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 8.7,
      doubanScore: 9.4,
      imdbUrl: "https://www.imdb.com/title/tt0816692/",
      doubanUrl: "https://movie.douban.com/subject/1889243/",
      markedAt: "2026-09-15",
      poster: "assets/posters/interstellar.jpg",
      posterPreview: "assets/posters/interstellar-display.jpg",
      posterThumb: "assets/posters/interstellar-thumb.jpg",
      backdrop: "assets/backdrops/interstellar.jpg",
      backdropPosition: "50% 65%",
      backdropPositionMobile: "65% 65%",
      tagline: "一小时，七年。",
      summary:
        "沙尘暴正在吞掉地球。前宇航员穿过土星旁的虫洞去找宜居星球，而在另一颗星球上，一小时等于地球上的七年。",
      review: "",
    },
    {
      id: "oppenheimer",
      title: "奥本海默",
      originalTitle: "Oppenheimer",
      enTitle: "Oppenheimer",
      year: 2023,
      director: "克里斯托弗·诺兰",
      cast: ["基里安·墨菲", "艾米莉·布朗特", "马特·达蒙", "小罗伯特·唐尼"],
      genres: ["传记", "剧情", "历史"],
      country: "美国",
      runtime: 180,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 8.2,
      doubanScore: 8.8,
      imdbUrl: "https://www.imdb.com/title/tt15398776/",
      doubanUrl: "https://movie.douban.com/subject/35593344/",
      markedAt: "2026-09-19",
      poster: "assets/posters/oppenheimer.jpg",
      posterPreview: "assets/posters/oppenheimer-display.jpg",
      posterThumb: "assets/posters/oppenheimer-thumb.jpg",
      backdrop: "assets/backdrops/oppenheimer.jpg",
      backdropPosition: "50% 40%",
      tagline: "沙漠里的那道光。",
      summary:
        "洛斯阿拉莫斯实验室里，他把人类第一次核爆点亮在新墨西哥的沙漠上。战后的听证会里，同一个人被一点点拆开。",
      review: "",
    },
    {
      id: "inception",
      title: "盗梦空间",
      originalTitle: "Inception",
      enTitle: "Inception",
      year: 2010,
      director: "克里斯托弗·诺兰",
      cast: ["莱昂纳多·迪卡普里奥", "约瑟夫·高登-莱维特", "艾伦·佩吉", "汤姆·哈迪"],
      genres: ["科幻", "悬疑", "动作"],
      country: "美国",
      runtime: 148,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 8.8,
      doubanScore: 9.4,
      imdbUrl: "https://www.imdb.com/title/tt1375666/",
      doubanUrl: "https://movie.douban.com/subject/3541415/",
      markedAt: "2026-09-22",
      poster: "assets/posters/inception.jpg",
      posterPreview: "assets/posters/inception-display.jpg",
      posterThumb: "assets/posters/inception-thumb.jpg",
      backdrop: "assets/backdrops/inception.jpg",
      backdropPosition: "50% 40%",
      tagline: "一颗念头的重量。",
      summary:
        "潜入他人梦境窃取秘密的团队，接下了一个相反的任务：往目标的潜意识里种下一个念头。梦一层层往下，回程却越来越难。",
      review: "",
    },
    {
      id: "blade-runner-2049",
      title: "银翼杀手2049",
      originalTitle: "Blade Runner 2049",
      enTitle: "Blade Runner 2049",
      year: 2017,
      director: "丹尼斯·维伦纽瓦",
      cast: ["瑞恩·高斯林", "哈里森·福特", "安娜·德·阿玛斯", "西尔维娅·侯克斯", "杰瑞德·莱托"],
      genres: ["科幻", "剧情", "悬疑"],
      country: "美国",
      runtime: 164,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 8,
      doubanScore: 8.3,
      imdbUrl: "https://www.imdb.com/title/tt1856101/",
      doubanUrl: "https://movie.douban.com/subject/10512661/",
      markedAt: null,
      poster: "assets/posters/blade-runner-2049.jpg",
      posterPreview: "assets/posters/blade-runner-2049-display.jpg",
      posterThumb: "assets/posters/blade-runner-2049-thumb.jpg",
      backdrop: "assets/backdrops/blade-runner-2049.jpg",
      backdropPosition: "50% 40%",
      tagline: "记忆是真的，就无所谓真假。",
      summary:
        "近未来洛杉矶，银翼杀手K在一次例行清剿中挖出一具遗骸，牵出复制人曾自然生育的秘密。为了销毁证据，他去找失踪三十年的前银翼杀手迪卡德，却在追查中开始怀疑，自己脑中的童年记忆或许并不是被植入的。",
      review: "",
    },
    {
      id: "look-back",
      title: "蓦然回首",
      originalTitle: "ルックバック",
      enTitle: "Look Back",
      year: 2024,
      director: "押山清高",
      cast: ["河合优实", "吉田美月喜"],
      genres: ["动画", "剧情"],
      country: "日本",
      runtime: 58,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 7.8,
      doubanScore: 8.1,
      imdbUrl: "https://www.imdb.com/title/tt31711040/",
      doubanUrl: "https://movie.douban.com/subject/36727828/",
      markedAt: null,
      poster: "assets/posters/look-back.jpg",
      posterPreview: "assets/posters/look-back-display.jpg",
      posterThumb: "assets/posters/look-back-thumb.jpg",
      backdrop: "assets/backdrops/look-back.jpg",
      backdropPosition: "50% 45%",
      backdropPositionMobile: "50% 45%",
      tagline: "为什么要画画呢。",
      summary:
        "改编自藤本树同名短篇：在小镇校报上画四格漫画的藤野，被请长假宅家画画的同学京子追上，从此较着劲一路画下去。两人一起画画、一起长大的时光，在一场变故之后，成了藤野回望来路的支点。",
      review: "",
    },
    // 岩井俊二三部：个人评分、日期与短评待补。
    // 海报改为单片发行版，版本与原图 URL 见 ASSET-SOURCES.md；旧周年影展图保留但不再引用。
    // 资料：https://filmmovement.com/press/film/love-letter
    {
      id: "love-letter",
      title: "情书",
      originalTitle: "Love Letter",
      enTitle: "Love Letter",
      year: 1995,
      director: "岩井俊二",
      cast: ["中山美穗", "丰川悦司", "酒井美纪", "柏原崇"],
      genres: ["剧情", "爱情"],
      country: "日本",
      runtime: 117,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 7.9,
      doubanScore: 8.9,
      imdbUrl: "https://www.imdb.com/title/tt0113703/",
      doubanUrl: "https://movie.douban.com/subject/1292220/",
      markedAt: null,
      poster: "assets/posters/love-letter-cn-2021.jpg",
      posterPreview: "assets/posters/love-letter-cn-2021-display.jpg",
      posterThumb: "assets/posters/love-letter-cn-2021-thumb.jpg",
      backdrop: "assets/backdrops/love-letter.jpg",
      backdropPosition: "50% 35%",
      backdropPositionMobile: "28% 35%",
      tagline: "一封信，寄回了未曾说出口的青春。",
      summary:
        "未婚夫藤井树因山难去世后，渡边博子向他少年时住过的小樽地址寄出一封信，意外收到了另一位同名女子的回信。两人的书信往来，让一段藏在校园与旧书里的少年心事逐渐浮现。",
      review: "",
    },
    // 资料：https://jfdb.jp/title/200
    {
      id: "hana-and-alice",
      title: "花与爱丽丝",
      originalTitle: "花とアリス",
      enTitle: "Hana and Alice",
      year: 2004,
      director: "岩井俊二",
      cast: ["铃木杏", "苍井优", "郭智博"],
      genres: ["剧情", "喜剧", "爱情"],
      country: "日本",
      runtime: 135,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 7.2,
      doubanScore: 8.3,
      imdbUrl: "https://www.imdb.com/title/tt0407851/",
      doubanUrl: "https://movie.douban.com/subject/1308820/",
      markedAt: null,
      poster: "assets/posters/hana-and-alice-jp.jpg",
      posterPreview: "assets/posters/hana-and-alice-jp-display.jpg",
      posterThumb: "assets/posters/hana-and-alice-jp-thumb.jpg",
      backdrop: "assets/backdrops/hana-and-alice.jpg",
      backdropPosition: "50% 40%",
      tagline: "谎言绕了一圈，友情还在。",
      summary:
        "从小一起长大的花与爱丽丝升入高中。花暗恋的学长宫本意外撞到头，她趁机谎称两人早已交往；为了圆谎，爱丽丝也被拉进这场假装失忆的恋爱，三个人的关系渐渐变得微妙。",
      review: "",
    },
    // 资料：https://iwaifilm30th.com/archives/lineup/aprilstory
    {
      id: "april-story",
      title: "四月物语",
      originalTitle: "四月物語",
      enTitle: "April Story",
      year: 1998,
      director: "岩井俊二",
      cast: ["松隆子", "田边诚一", "藤井香织", "加藤和彦"],
      genres: ["爱情"],
      country: "日本",
      runtime: 67,
      myScore: null,
      scoreStatus: "unrated",
      imdbScore: 7.1,
      doubanScore: 8.3,
      doubanNote: "豆瓣 8.3 来自 2026-03-27 新浪电影博主转述，尚待豆瓣源站复核。",
      imdbUrl: "https://www.imdb.com/title/tt0146271/",
      doubanUrl: "https://movie.douban.com/subject/1292371/",
      markedAt: null,
      poster: "assets/posters/april-story-jp.jpg",
      posterPreview: "assets/posters/april-story-jp-display.jpg",
      posterThumb: "assets/posters/april-story-jp-thumb.jpg",
      backdrop: "assets/backdrops/april-story.jpg",
      backdropPosition: "50% 40%",
      tagline: "为了一个人，来到一座城。",
      summary:
        "四月，北海道女孩榆野卯月独自来到东京，开始大学生活。在搬家、结识邻居与同学的日常里，她反复走进一间书店；她选择这所大学的秘密，也藏在店里那位曾让她心动的学长身上。",
      review: "",
    },
  ],
};
